[build]
  command = "chmod +x ./install-flutter.sh && ./install-flutter.sh && $HOME/flutter/bin/flutter build web"
  publish = "build/web"

[build.environment]
  FLUTTER_CHANNEL = "stable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
