name: storyspark
description: A kid-friendly app for creating AI-generated stories.
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  video_player: ^2.9.1  # Add this line
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    
    - assets/background.jpg
    - assets/logo.png
    - assets/spark_a_story_button.png
    - assets/my_vault_button.png
    - assets/publish_button.png
    - assets/signup_button.png  # New cloud login button
    - assets/login_button.png   # New cloud login button
    - assets/how_to_scroll.mp4  # Add your video file here